version: '3.7'
services:
  client:
    image: construct-co-web
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server
    environment:
      PORT: 3000
  server:
    image: construct-co-backend
    build: ./server
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      HOST: '0.0.0.0'